### ISSUE TITLE
[BUG] Visual glitch with Tidy5e Sheet

### ISSUE THREAD

**Issue by RaylaTheBrave** [p4535992/foundryvtt-character-actions-dnd5e#1]
**Module Version:**
-  Tidy5e Sheet: Version 0.8.16.
- Character Actions List dnd5e: Version 6.0.2.

**Describe the bug**
Visual dealignment between range, hit/dc and damage fields and its list elements in the action menu inside the character sheet if using Tidy5e Sheet. Also the headers of the lists are a bit too broad and I don't know if that's the intention.

**To Reproduce**
1. Open the character sheet.
2. Go to the action section of the sheet.

**Expected behavior**
To have the range, hit/dc and damage fields align with its list elements.

**Screenshots**
![glitch](https://user-images.githubusercontent.com/123700650/216954063-8ca0af7d-59b7-49ab-957c-11d7860cd27a.PNG)

**Browser:**
Desktop app.

**Foundry Version:** 
Version 10, Build 291.

**Game System:** 
DnD 5e. Version: 2.1.4.

**Additional context**
None at the moment.

**Comment by OxTailSafu** [comment]
I can corroborate that this issue also occurs ever since update .8.14 on Tidysheet. I've also noticed that I can no longer add spells onto the action's list as right clicking does not show an option to add it as seen below.

![image](https://user-images.githubusercontent.com/123988485/217329502-4222e1f1-b25a-4e16-9710-ac97e858218f.png)

This means once you remove a spell from the actions list, you can no longer re-add them. The same can occur to features unless you select the option to use classic controls from the module settings.
